package simple;

import java.util.HashMap;
import java.util.Map;

public class AsciiArt {

    // Map to store ASCII representations of each character
    private static final Map<Character, String[]> asciiMap = new HashMap<>();

    // getter for asciiMap
    public static Map<Character, String[]> getAsciiMap() {
        return asciiMap;
    }

    // Initialize the ASCII art map with representations for each letter
    static {
        asciiMap.put(' ', new String[]{
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
            "         ",
        });
        asciiMap.put('A', new String[]{
                "                                 ",
                "               AAA               ",
                "              A:::A              ",
                "             A:::::A             ",
                "            A:::::::A            ",
                "           A:::::::::A           ",
                "          A:::::A:::::A          ",
                "         A:::::A A:::::A         ",
                "        A:::::A   A:::::A        ",
                "       A:::::A     A:::::A       ",
                "      A:::::AAAAAAAAA:::::A      ",
                "     A:::::::::::::::::::::A     ",
                "    A:::::AAAAAAAAAAAAA:::::A    ",
                "   A:::::A             A:::::A   ",
                "  A:::::A               A:::::A  ",
                " A:::::A                 A:::::A ",
                "AAAAAAA                   AAAAAAA",
                "                                 ",
                "                                 ",
                "                                 ",
                "                                 ",
                "                                 ",
                "                                 ",
                "                                 ",
        });
        asciiMap.put('B', new String[]{
                "                    ",
                "BBBBBBBBBBBBBBBBB   ",
                "B::::::::::::::::B  ",
                "B::::::BBBBBB:::::B ",
                "BB:::::B     B:::::B",
                "  B::::B     B:::::B",
                "  B::::B     B:::::B",
                "  B::::BBBBBB:::::B ",
                "  B:::::::::::::BB  ",
                "  B::::BBBBBB:::::B ",
                "  B::::B     B:::::B",
                "  B::::B     B:::::B",
                "  B::::B     B:::::B",
                "BB:::::BBBBBB::::::B",
                "B:::::::::::::::::B ",
                "B::::::::::::::::B  ",
                "BBBBBBBBBBBBBBBBB   ",
                "                    ",
                "                    ",
                "                    ",
                "                    ",
                "                    ",
                "                    ",
                "                    ",
        });
        asciiMap.put('C', new String[]{
                "                     ",
                "        CCCCCCCCCCCCC",
                "     CCC::::::::::::C",
                "   CC:::::::::::::::C",
                "  C:::::CCCCCCCC::::C",
                " C:::::C       CCCCCC",
                "C:::::C              ",
                "C:::::C              ",
                "C:::::C              ",
                "C:::::C              ",
                "C:::::C              ",
                "C:::::C              ",
                " C:::::C       CCCCCC",
                "  C:::::CCCCCCCC::::C",
                "   CC:::::::::::::::C",
                "     CCC::::::::::::C",
                "        CCCCCCCCCCCCC",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
        });
        asciiMap.put('D', new String[]{
                "                     ",
                "DDDDDDDDDDDDD        ",
                "D::::::::::::DDD     ",
                "D:::::::::::::::DD   ",
                "DDD:::::DDDDD:::::D  ",
                "  D:::::D    D:::::D ",
                "  D:::::D     D:::::D",
                "  D:::::D     D:::::D",
                "  D:::::D     D:::::D",
                "  D:::::D     D:::::D",
                "  D:::::D     D:::::D",
                "  D:::::D     D:::::D",
                "  D:::::D    D:::::D ",
                "DDD:::::DDDDD:::::D  ",
                "D:::::::::::::::DD   ",
                "D::::::::::::DDD     ",
                "DDDDDDDDDDDDD        ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
        });
        asciiMap.put('E', new String[]{
                "                      ",
                "EEEEEEEEEEEEEEEEEEEEEE",
                "E::::::::::::::::::::E",
                "E::::::::::::::::::::E",
                "EE::::::EEEEEEEEE::::E",
                "  E:::::E       EEEEEE",
                "  E:::::E             ",
                "  E::::::EEEEEEEEEE   ",
                "  E:::::::::::::::E   ",
                "  E:::::::::::::::E   ",
                "  E::::::EEEEEEEEEE   ",
                "  E:::::E             ",
                "  E:::::E       EEEEEE",
                "EE::::::EEEEEEEE:::::E",
                "E::::::::::::::::::::E",
                "E::::::::::::::::::::E",
                "EEEEEEEEEEEEEEEEEEEEEE",
                "                      ",
                "                      ",
                "                      ",
                "                      ",
                "                      ",
                "                      ",
                "                      ",
        });
        asciiMap.put('F', new String[]{
                "                      ",
                "FFFFFFFFFFFFFFFFFFFFFF",
                "F::::::::::::::::::::F",
                "F::::::::::::::::::::F",
                "FF::::::FFFFFFFFF::::F",
                "  F:::::F       FFFFFF",
                "  F:::::F             ",
                "  F::::::FFFFFFFFFF   ",
                "  F:::::::::::::::F   ",
                "  F:::::::::::::::F   ",
                "  F::::::FFFFFFFFFF   ",
                "  F:::::F             ",
                "  F:::::F             ",
                "FF:::::::FF           ",
                "F::::::::FF           ",
                "F::::::::FF           ",
                "FFFFFFFFFFF           ",
                "                      ",
                "                      ",
                "                      ",
                "                      ",
                "                      ",
                "                      ",
                "                      ",
        });
        asciiMap.put('G', new String[]{
                "                     ",
                "        GGGGGGGGGGGGG",
                "     GGG::::::::::::G",
                "   GG:::::::::::::::G",
                "  G:::::GGGGGGGG::::G",
                " G:::::G       GGGGGG",
                "G:::::G              ",
                "G:::::G              ",
                "G:::::G    GGGGGGGGGG",
                "G:::::G    G::::::::G",
                "G:::::G    GGGGG::::G",
                "G:::::G        G::::G",
                " G:::::G       G::::G",
                "  G:::::GGGGGGGG::::G",
                "   GG:::::::::::::::G",
                "     GGG::::::GGG:::G",
                "        GGGGGG   GGGG",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
        });
        asciiMap.put('H', new String[]{
                "                       ",
                "HHHHHHHHH     HHHHHHHHH",
                "H:::::::H     H:::::::H",
                "H:::::::H     H:::::::H",
                "HH::::::H     H::::::HH",
                "  H:::::H     H:::::H  ",
                "  H:::::H     H:::::H  ",
                "  H::::::HHHHH::::::H  ",
                "  H:::::::::::::::::H  ",
                "  H:::::::::::::::::H  ",
                "  H::::::HHHHH::::::H  ",
                "  H:::::H     H:::::H  ",
                "  H:::::H     H:::::H  ",
                "HH::::::H     H::::::HH",
                "H:::::::H     H:::::::H",
                "H:::::::H     H:::::::H",
                "HHHHHHHHH     HHHHHHHHH",
                "                       ",
                "                       ",
                "                       ",
                "                       ",
                "                       ",
                "                       ",
                "                       ",
        });
        asciiMap.put('I', new String[]{
                "          ",
                "IIIIIIIIII",
                "I::::::::I",
                "I::::::::I",
                "II::::::II",
                "  I::::I  ",
                "  I::::I  ",
                "  I::::I  ",
                "  I::::I  ",
                "  I::::I  ",
                "  I::::I  ",
                "  I::::I  ",
                "  I::::I  ",
                "II::::::II",
                "I::::::::I",
                "I::::::::I",
                "IIIIIIIIII",
                "          ",
                "          ",
                "          ",
                "          ",
                "          ",
                "          ",
                "          ",
        });
        asciiMap.put('J', new String[]{
                "                     ",
                "          JJJJJJJJJJJ",
                "          J:::::::::J",
                "          J:::::::::J",
                "          JJ:::::::JJ",
                "            J:::::J  ",
                "            J:::::J  ",
                "            J:::::J  ",
                "            J:::::j  ",
                "            J:::::J  ",
                "JJJJJJJ     J:::::J  ",
                "J:::::J     J:::::J  ",
                "J::::::J   J::::::J  ",
                "J:::::::JJJ:::::::J  ",
                " JJ:::::::::::::JJ   ",
                "   JJ:::::::::JJ     ",
                "     JJJJJJJJJ       ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
        });
        asciiMap.put('K', new String[]{
                "                    ",
                "KKKKKKKKK    KKKKKKK",
                "K:::::::K    K:::::K",
                "K:::::::K    K:::::K",
                "K:::::::K   K::::::K",
                "KK::::::K  K:::::KKK",
                "  K:::::K K:::::K   ",
                "  K::::::K:::::K    ",
                "  K:::::::::::K     ",
                "  K:::::::::::K     ",
                "  K::::::K:::::K    ",
                "  K:::::K K:::::K   ",
                "KK::::::K  K:::::KKK",
                "K:::::::K   K::::::K",
                "K:::::::K    K:::::K",
                "K:::::::K    K:::::K",
                "KKKKKKKKK    KKKKKKK",
                "                    ",
                "                    ",
                "                    ",
                "                    ",
                "                    ",
                "                    ",
                "                    ",
        });
        asciiMap.put('L', new String[]{
                "                        ",
                "LLLLLLLLLLL             ",
                "L:::::::::L             ",
                "L:::::::::L             ",
                "LL:::::::LL             ",
                "  L:::::L               ",
                "  L:::::L               ",
                "  L:::::L               ",
                "  L:::::L               ",
                "  L:::::L               ",
                "  L:::::L               ",
                "  L:::::L               ",
                "  L:::::L         LLLLLL",
                "LL:::::::LLLLLLLLL:::::L",
                "L::::::::::::::::::::::L",
                "L::::::::::::::::::::::L",
                "LLLLLLLLLLLLLLLLLLLLLLLL",
                "                        ",
                "                        ",
                "                        ",
                "                        ",
                "                        ",
                "                        ",
                "                        ",
        });
        asciiMap.put('M', new String[]{
                "                               ",
                "MMMMMMMM               MMMMMMMM",
                "M:::::::M             M:::::::M",
                "M::::::::M           M::::::::M",
                "M:::::::::M         M:::::::::M",
                "M::::::::::M       M::::::::::M",
                "M:::::::::::M     M:::::::::::M",
                "M:::::::M::::M   M::::M:::::::M",
                "M::::::M M::::M M::::M M::::::M",
                "M::::::M  M::::M::::M  M::::::M",
                "M::::::M   M:::::::M   M::::::M",
                "M::::::M    M:::::M    M::::::M",
                "M::::::M     MMMMM     M::::::M",
                "M::::::M               M::::::M",
                "M::::::M               M::::::M",
                "M::::::M               M::::::M",
                "MMMMMMMM               MMMMMMMM",
                "                               ",
                "                               ",
                "                               ",
                "                               ",
                "                               ",
                "                               ",
                "                               ",
        });
        asciiMap.put('N', new String[]{
                "                        ",
                "NNNNNNNN        NNNNNNNN",
                "N:::::::N       N::::::N",
                "N::::::::N      N::::::N",
                "N:::::::::N     N::::::N",
                "N::::::::::N    N::::::N",
                "N:::::::::::N   N::::::N",
                "N:::::::N::::N  N::::::N",
                "N::::::N N::::N N::::::N",
                "N::::::N  N::::N:::::::N",
                "N::::::N   N:::::::::::N",
                "N::::::N    N::::::::::N",
                "N::::::N     N:::::::::N",
                "N::::::N      N::::::::N",
                "N::::::N       N:::::::N",
                "N::::::N        N::::::N",
                "NNNNNNNN         NNNNNNN",
                "                        ",
                "                        ",
                "                        ",
                "                        ",
                "                        ",
                "                        ",
                "                        ",
        });
        asciiMap.put('O', new String[]{
                "                   ",
                "     OOOOOOOOO     ",
                "   OO:::::::::OO   ",
                " OO:::::::::::::OO ",
                "O:::::::OOO:::::::O",
                "O::::::O   O::::::O",
                "O:::::O     O:::::O",
                "O:::::O     O:::::O",
                "O:::::O     O:::::O",
                "O:::::O     O:::::O",
                "O:::::O     O:::::O",
                "O:::::O     O:::::O",
                "O::::::O   O::::::O",
                "O:::::::OOO:::::::O",
                " OO:::::::::::::OO ",
                "  OO:::::::::OO    ",
                "     OOOOOOOOO     ",
                "                   ",
                "                   ",
                "                   ",
                "                   ",
                "                   ",
                "                   ",
                "                   ",
        });
        asciiMap.put('P', new String[]{
                "                    ",
                "PPPPPPPPPPPPPPPPP   ",
                "P::::::::::::::::P  ",
                "P::::::PPPPPP:::::P ",
                "PP:::::P     P:::::P",
                "  P::::P     P:::::P",
                "  P::::P     P:::::P",
                "  P::::PPPPPP:::::P ",
                "  P:::::::::::::PP  ",
                "  P::::PPPPPPPPP    ",
                "  P::::P            ",
                "  P::::P            ",
                "  P::::P            ",
                "PP::::::PP          ",
                "P::::::::P          ",
                "P::::::::P          ",
                "PPPPPPPPPP          ",
                "                    ",
                "                    ",
                "                    ",
                "                    ",
                "                    ",
                "                    ",
                "                    ",
        });
        asciiMap.put('Q', new String[]{
                "                    ",
                "     QQQQQQQQQ      ", 
                "   QQ:::::::::QQ    ", 
                " QQ:::::::::::::QQ  ",
                "Q:::::::QQQ:::::::Q ", 
                "Q::::::O   Q::::::Q ", 
                "Q:::::O     Q:::::Q ", 
                "Q:::::O     Q:::::Q ", 
                "Q:::::O     Q:::::Q ",
                "Q:::::O     Q:::::Q ",
                "Q:::::O     Q:::::Q ",
                "Q:::::O  QQQQ:::::Q ",
                "Q::::::O Q::::::::Q ",
                "Q:::::::QQ::::::::Q ",
                " QQ::::::::::::::Q  ",
                "   QQ:::::::::::Q   ",
                "     QQQQQQQQ::::QQ ",
                "             Q:::::Q",
                "              QQQQQQ",
                "                    ",
                "                    ",
                "                    ",
                "                    ",
                "                    ",
        });
        asciiMap.put('R', new String[]{
                "                    ",
                "RRRRRRRRRRRRRRRRR   ",
                "R::::::::::::::::R  ",
                "R::::::RRRRRR:::::R ",
                "RR:::::R     R:::::R",
                "  R::::R     R:::::R",
                "  R::::R     R:::::R",
                "  R::::RRRRRR:::::R ",
                "  R:::::::::::::RR  ",
                "  R::::RRRRRR:::::R ",
                "  R::::R     R:::::R",
                "  R::::R     R:::::R",
                "  R::::R     R:::::R",
                "RR:::::R     R:::::R",
                "R::::::R     R:::::R",
                "R::::::R     R:::::R",
                "RRRRRRRR     RRRRRRR",
                "                    ",
                "                    ",
                "                    ",
                "                    ",
                "                    ",
                "                    ",
                "                    ",
        });
        asciiMap.put('S', new String[]{
                "                   ",
                "   SSSSSSSSSSSSSSS ",
                " SS:::::::::::::::S",
                "S:::::SSSSSS::::::S",
                "S:::::S     SSSSSSS",
                "S:::::S            ",
                "S:::::S            ",
                " S::::SSSS         ",
                "  SS::::::SSSSS    ",
                "    SSS::::::::SS  ",
                "       SSSSSS::::S ",
                "            S:::::S",
                "            S:::::S",
                "SSSSSSS     S:::::S",
                "S::::::SSSSSS:::::S",
                "S:::::::::::::::SS ",
                " SSSSSSSSSSSSSSS   ",
                "                   ",
                "                   ",
                "                   ",
                "                   ",
                "                   ",
                "                   ",
                "                   ",
        });
        asciiMap.put('T', new String[]{
                "                       ",
                "TTTTTTTTTTTTTTTTTTTTTTT",
                "T:::::::::::::::::::::T",
                "T:::::::::::::::::::::T",
                "T:::::TT:::::::TT:::::T",
                "TTTTTT  T:::::T  TTTTTT",
                "        T:::::T        ",
                "        T:::::T        ",
                "        T:::::T        ",
                "        T:::::T        ",
                "        T:::::T        ",
                "        T:::::T        ",
                "        T:::::T        ",
                "      TT:::::::TT      ",
                "      T:::::::::T      ",
                "      T:::::::::T      ",
                "      TTTTTTTTTTT      ",
                "                       ",
                "                       ",
                "                       ",
                "                       ",
                "                       ",
                "                       ",
                "                       ",
        });
        asciiMap.put('U', new String[]{
                "                     ",
                "UUUUUUUU     UUUUUUUU",
                "U::::::U     U::::::U",
                "U::::::U     U::::::U",
                "UU:::::U     U:::::UU",
                " U:::::U     U:::::U ",
                " U:::::D     D:::::U ",
                " U:::::D     D:::::U ",
                " U:::::D     D:::::U ",
                " U:::::D     D:::::U ",
                " U:::::D     D:::::U ",
                " U:::::D     D:::::U ",
                " U::::::U   U::::::U ",
                " U:::::::UUU:::::::U ",
                "  UU:::::::::::::UU  ",
                "    UU:::::::::UU    ",
                "      UUUUUUUUU      ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
        });
        asciiMap.put('V', new String[]{
                "                           ",
                "VVVVVVVV           VVVVVVVV",
                "V::::::V           V::::::V",
                "V::::::V           V::::::V",
                "V::::::V           V::::::V",
                " V:::::V           V:::::V ",
                "  V:::::V         V:::::V  ",
                "   V:::::V       V:::::V   ",
                "    V:::::V     V:::::V    ",
                "     V:::::V   V:::::V     ",
                "      V:::::V V:::::V       ",
                "       V:::::V:::::V       ",
                "        V:::::::::V        ",
                "         V:::::::V         ",
                "          V:::::V          ",
                "           V:::V           ",
                "            VVV            ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
                "                           ",
        });
        asciiMap.put('W', new String[]{
                "                                           ",
                "WWWWWWWW                           WWWWWWWW",
                "W::::::W                           W::::::W",
                "W::::::W                           W::::::W",
                "W::::::W                           W::::::W",
                " W:::::W           WWWWW           W:::::W ",
                "  W:::::W         W:::::W         W:::::W  ",
                "   W:::::W       W:::::::W       W:::::W   ",
                "    W:::::W     W:::::::::W     W:::::W    ",
                "     W:::::W   W:::::W:::::W   W:::::W     ",
                "      W:::::W W:::::W W:::::W W:::::W      ",
                "       W:::::W:::::W   W:::::W:::::W       ",
                "        W:::::::::W     W:::::::::W        ",
                "         W:::::::W       W:::::::W         ",
                "          W:::::W         W:::::W          ",
                "           W:::W           W:::W           ",
                "            WWW             WWW            ",
                "                                           ",
                "                                           ",
                "                                           ",
                "                                           ",
                "                                           ",
                "                                           ",
                "                                           ",
        });
        asciiMap.put('X', new String[]{
                "                     ",
                "XXXXXXX       XXXXXXX",
                "X:::::X       X:::::X",
                "X:::::X       X:::::X",
                "X::::::X     X::::::X",
                "XXX:::::X   X:::::XXX",
                "   X:::::X X:::::X   ",
                "    X:::::X:::::X    ",
                "     X:::::::::X     ",
                "     X:::::::::X     ",
                "    X:::::X:::::X    ",
                "   X:::::X X:::::X   ",
                "XXX:::::X   X:::::XXX",
                "X::::::X     X::::::X",
                "X:::::X       X:::::X",
                "X:::::X       X:::::X",
                "XXXXXXX       XXXXXXX",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
        });
        asciiMap.put('Y', new String[]{
                "                     ",    
                "YYYYYYY       YYYYYYY",
                "Y:::::Y       Y:::::Y",
                "Y:::::Y       Y:::::Y",
                "Y::::::Y     Y::::::Y",
                "YYY:::::Y   Y:::::YYY",
                "   Y:::::Y Y:::::Y   ",
                "    Y:::::Y:::::Y    ",
                "     Y:::::::::Y     ",
                "      Y:::::::Y      ",
                "       Y:::::Y       ",
                "       Y:::::Y       ",
                "       Y:::::Y       ",
                "       Y:::::Y       ",
                "    YYYY:::::YYYY    ",
                "    Y:::::::::::Y    ",
                "    YYYYYYYYYYYYY    ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
                "                     ",
        });
        asciiMap.put('Z', new String[]{
                "                   ",
                "ZZZZZZZZZZZZZZZZZZZ",
                "Z:::::::::::::::::Z",
                "Z:::::::::::::::::Z",
                "Z:::ZZZZZZZZ:::::Z ",
                "ZZZZZ     Z:::::Z  ",
                "        Z:::::Z    ",
                "       Z:::::Z     ",
                "      Z:::::Z      ",
                "     Z:::::Z       ",
                "    Z:::::Z        ",
                "   Z:::::Z         ",
                "ZZZ:::::Z     ZZZZZ",
                "Z::::::ZZZZZZZZ:::Z",
                "Z:::::::::::::::::Z",
                "Z:::::::::::::::::Z",
                "ZZZZZZZZZZZZZZZZZZZ",
                "                   ",
                "                   ",
                "                   ",
                "                   ",
                "                   ",
                "                   ",
                "                   ",
        });
        asciiMap.put('a', new String[]{
            "                  ",
            "                  ",
            "                  ",
            "                  ",
            "                  ",
            "  aaaaaaaaaaaaa   ",
            "  a::::::::::::a  ",
            "  aaaaaaaaa:::::a ",
            "           a::::a ",
            "    aaaaaaa:::::a ",
            "  aa::::::::::::a ",
            " a::::aaaa::::::a ",
            "a::::a    a:::::a ",
            "a::::a    a:::::a ",
            "a:::::aaaa::::::a ",
            " a::::::::::aa:::a",
            "  aaaaaaaaaa  aaaa",
            "                  ",
            "                  ",
            "                  ",
            "                  ",
            "                  ",
            "                  ",
            "                  ",
        });
        asciiMap.put('b', new String[]{
            "bbbbbbbb            ",
            "b::::::b            ",
            "b::::::b            ",
            "b::::::b            ",
            " b:::::b            ",
            " b:::::bbbbbbbbb    ",
            " b::::::::::::::bb  ",
            " b::::::::::::::::b ",
            " b:::::bbbbb:::::::b",
            " b:::::b    b::::::b",
            " b:::::b     b:::::b",
            " b:::::b     b:::::b",
            " b:::::b     b:::::b",
            " b:::::bbbbbb::::::b",
            " b::::::::::::::::b ",
            " b:::::::::::::::b  ",
            " bbbbbbbbbbbbbbbb   ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
        });
        asciiMap.put('c', new String[]{
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "    cccccccccccccccc",
            "  cc:::::::::::::::c",
            " c:::::::::::::::::c",
            "c:::::::cccccc:::::c",
            "c::::::c     ccccccc",
            "c:::::c             ",
            "c:::::c             ",
            "c::::::c     ccccccc",
            "c:::::::cccccc:::::c",
            " c:::::::::::::::::c",
            "  cc:::::::::::::::c",
            "    cccccccccccccccc",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
        });
        asciiMap.put('d', new String[]{
            "            dddddddd",
            "            d::::::d",
            "            d::::::d",
            "            d::::::d",
            "            d:::::d ",
            "    ddddddddd:::::d ",
            "  dd::::::::::::::d ",
            " d::::::::::::::::d ",
            "d:::::::ddddd:::::d ",
            "d::::::d    d:::::d ",
            "d:::::d     d:::::d ",
            "d:::::d     d:::::d ",
            "d:::::d     d:::::d ",
            "d::::::ddddd::::::dd",
            " d:::::::::::::::::d",
            "  d:::::::::ddd::::d",
            "   ddddddddd   ddddd",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
        });
        asciiMap.put('e', new String[]{
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "    eeeeeeeeeeee    ",
            "  ee::::::::::::ee  ",
            " e::::::eeeee:::::ee",
            "e::::::e     e:::::e",
            "e:::::::eeeee::::::e",
            "e:::::::::::::::::e ",
            "e::::::eeeeeeeeeee  ",
            "e:::::::e           ",
            "e::::::::e          ",
            " e::::::::eeeeeeee  ",
            "  ee:::::::::::::e  ",
            "    eeeeeeeeeeeeee  ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
        });
        asciiMap.put('f', new String[]{
            "                      ",
            "    ffffffffffffffff  ",
            "   f::::::::::::::::f ",
            "  f::::::::::::::::::f",
            "  f::::::fffffff:::::f",
            "  f:::::f       ffffff",
            "  f:::::f             ",
            " f:::::::ffffff       ",
            " f::::::::::::f       ",
            " f::::::::::::f       ",
            " f:::::::ffffff       ",
            "  f:::::f             ",
            "  f:::::f             ",
            " f:::::::f            ",
            " f:::::::f            ",
            " f:::::::f            ",
            " fffffffff            ",
            "                      ",
            "                      ",
            "                      ",
            "                      ",
            "                      ",
            "                      ",
            "                      ",
        });
        asciiMap.put('g', new String[]{
            "                    ",                     
            "                    ",
            "                    ",      
            "                    ",
            "                    ",
            "   ggggggggg   ggggg",
            "  g:::::::::ggg::::g",
            " g:::::::::::::::::g",
            "g::::::ggggg::::::gg",
            "g:::::g     g:::::g ",
            "g:::::g     g:::::g ",
            "g:::::g     g:::::g ",
            "g::::::g    g:::::g ",
            "g:::::::ggggg:::::g ",
            " g::::::::::::::::g ",
            "  gg::::::::::::::g ",
            "    gggggggg::::::g ",
            "            g:::::g ",
            "gggggg      g:::::g ",
            "g:::::gg   gg:::::g ",
            " g::::::ggg:::::::g ",
            "  gg:::::::::::::g  ",
            "    ggg::::::ggg    ",
            "       gggggg       ",
        });
        asciiMap.put('h', new String[]{
            "                    ",
            "hhhhhhh             ",
            "h:::::h             ",
            "h:::::h             ",
            "h:::::h             ",
            " h::::h hhhhh       ",
            " h::::hh:::::hhh    ",
            " h::::::::::::::hh  ",
            " h:::::::hhh::::::h ",
            " h::::::h   h::::::h",
            " h:::::h     h:::::h",
            " h:::::h     h:::::h",
            " h:::::h     h:::::h",
            " h:::::h     h:::::h",
            " h:::::h     h:::::h",
            " h:::::h     h:::::h",
            " hhhhhhh     hhhhhhh",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
        });
        asciiMap.put('i', new String[]{
            "        ",
            "  iiii  ",
            " i::::i ",
            "  iiii  ",
            "        ",
            "iiiiiii ",
            "i:::::i ",
            " i::::i ",
            " i::::i ",
            " i::::i ",
            " i::::i ",
            " i::::i ",
            " i::::i ",
            "i::::::i",
            "i::::::i",
            "i::::::i",
            "iiiiiiii",
            "        ",
            "        ",
            "        ",
            "        ",
            "        ",
            "        ",
            "        ",
        });
        asciiMap.put('j', new String[]{
            "                  ",
            "             jjjj ",
            "            j::::j",
            "             jjjj ",
            "                  ",
            "           jjjjjjj",
            "           j:::::j",
            "            j::::j",
            "            j::::j",
            "            j::::j",
            "            j::::j",
            "            j::::j",
            "            j::::j",
            "            j::::j",
            "            j::::j",
            "            j::::j",
            "            j::::j",
            "            j::::j",
            "  jjjj      j::::j",
            " j::::jj   j:::::j",
            " j::::::jjj::::::j",
            "  jj::::::::::::j ",
            "    jjj::::::jjj  ",
            "       jjjjjj     ",
        });
        asciiMap.put('k', new String[]{
            "                   ",
            "kkkkkkkk           ",
            "k::::::k           ",
            "k::::::k           ",
            "k::::::k           ",
            " k:::::k    kkkkkkk",
            " k:::::k   k:::::k ",
            " k:::::k  k:::::k  ",
            " k:::::k k:::::k   ",
            " k::::::k:::::k    ",
            " k:::::::::::k     ",
            " k:::::::::::k     ",
            " k::::::k:::::k    ",
            "k::::::k k:::::k   ",
            "k::::::k  k:::::k  ",
            "k::::::k   k:::::k ",
            "kkkkkkkk    kkkkkkk",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
        });
        asciiMap.put('l', new String[]{
            "        ",
            "lllllll ",
            "l:::::l ",
            "l:::::l ",
            "l:::::l ",
            " l::::l ",
            " l::::l ",
            " l::::l ",
            " l::::l ",
            " l::::l ",
            " l::::l ",
            " l::::l ",
            " l::::l ",
            "l::::::l",
            "l::::::l",
            "l::::::l",
            "llllllll",
            "        ",
            "        ",
            "        ",
            "        ",
            "        ",
            "        ",
            "        ",
        });
        asciiMap.put('m', new String[]{
            "                        ",
            "                        ",
            "                        ",
            "                        ",
            "                        ",
            "   mmmmmmm    mmmmmmm   ",
            " mm:::::::m  m:::::::mm ",
            "m::::::::::mm::::::::::m",
            "m::::::::::::::::::::::m",
            "m:::::mmm::::::mmm:::::m",
            "m::::m   m::::m   m::::m",
            "m::::m   m::::m   m::::m",
            "m::::m   m::::m   m::::m",
            "m::::m   m::::m   m::::m",
            "m::::m   m::::m   m::::m",
            "m::::m   m::::m   m::::m",
            "mmmmmm   mmmmmm   mmmmmm",
            "                        ",
            "                        ",
            "                        ",
            "                        ",
            "                        ",
            "                        ",
            "                        ",
        });
        asciiMap.put('n', new String[]{
            "                  ",
            "                  ",
            "                  ",
            "                  ",
            "                  ", 
            "nnnn  nnnnnnnn    ",
            "n:::nn::::::::nn  ",
            "n::::::::::::::nn ",
            "nn:::::::::::::::n",
            "  n:::::nnnn:::::n",
            "  n::::n    n::::n",
            "  n::::n    n::::n",
            "  n::::n    n::::n",
            "  n::::n    n::::n",
            "  n::::n    n::::n",
            "  n::::n    n::::n",
            "  nnnnnn    nnnnnn",
            "                  ",
            "                  ",
            "                  ",
            "                  ",
            "                  ",
            "                  ",
            "                  ",
        });
        asciiMap.put('o', new String[]{
            "                 ",
            "                 ",
            "                 ",
            "                 ",
            "                 ",
            "   ooooooooooo   ",
            " oo:::::::::::oo ",
            "o:::::::::::::::o",
            "o:::::ooooo:::::o",
            "o::::o     o::::o",
            "o::::o     o::::o",
            "o::::o     o::::o",
            "o::::o     o::::o",
            "o:::::ooooo:::::o",
            "o:::::::::::::::o",
            " oo:::::::::::oo ",
            "   ooooooooooo   ",
            "                 ",
            "                 ",
            "                 ",
            "                 ",
            "                 ",
            "                 ",
            "                 ",
        });
        asciiMap.put('p', new String[]{
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "ppppp   ppppppppp   ",
            "p::::ppp:::::::::p  ",
            "p:::::::::::::::::p ",
            "pp::::::ppppp::::::p",
            " p:::::p     p:::::p",
            " p:::::p     p:::::p",
            " p:::::p     p:::::p",
            " p:::::p    p::::::p",
            " p:::::ppppp:::::::p",
            " p::::::::::::::::p ",
            " p::::::::::::::pp  ",
            " p::::::pppppppp    ",
            " p:::::p            ",
            " p:::::p            ",
            "p:::::::p           ",
            "p:::::::p           ",
            "p:::::::p           ",
            "ppppppppp           ",
            "                    ",
        });
        asciiMap.put('q', new String[]{
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "   qqqqqqqqq   qqqqq",
            "  q:::::::::qqq::::q",
            " q:::::::::::::::::q",
            "q::::::qqqqq::::::qq",
            "q:::::q     q:::::q ",
            "q:::::q     q:::::q ",
            "q:::::q     q:::::q ",
            "q::::::q    q:::::q ",
            "q:::::::qqqqq:::::q ",
            " q::::::::::::::::q ",
            "  qq::::::::::::::q ",
            "    qqqqqqqq::::::q ",
            "            q:::::q ",
            "            q:::::q ",
            "           q:::::::q",
            "           q:::::::q",
            "           q:::::::q",
            "           qqqqqqqqq",
            "                    ",
        });
        asciiMap.put('r', new String[]{
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "rrrrr   rrrrrrrrr   ",
            "r::::rrr:::::::::r  ",
            "r:::::::::::::::::r ",
            "rr::::::rrrrr::::::r",
            " r:::::r     r:::::r",
            " r:::::r     rrrrrrr",
            " r:::::r            ",
            " r:::::r            ",
            " r:::::r            ",
            " r:::::r            ",
            " r:::::r            ",
            " rrrrrrr            ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
        });
        asciiMap.put('s', new String[]{
            "                 ", 
            "                 ", 
            "                 ", 
            "                 ", 
            "                 ", 
            "    ssssssssss   ",
            "  ss::::::::::s  ",
            "ss:::::::::::::s ",
            "s::::::ssss:::::s",
            " s:::::s  ssssss ",
            "   s::::::s      ",
            "      s::::::s   ",
            "ssssss   s:::::s ",
            "s:::::ssss::::::s",
            "s::::::::::::::s ",
            " s:::::::::::ss  ",
            "  sssssssssss    ",
            "                 ", 
            "                 ", 
            "                 ", 
            "                 ", 
            "                 ", 
            "                 ", 
            "                 ", 
        });
        asciiMap.put('t', new String[]{
            "                       ",
            "         tttt          ",
            "      ttt:::t          ",
            "      t:::::t          ",
            "      t:::::t          ",
            "ttttttt:::::ttttttt    ",
            "t:::::::::::::::::t    ",
            "t:::::::::::::::::t    ",
            "tttttt:::::::tttttt    ",
            "      t:::::t          ",
            "      t:::::t          ",
            "      t:::::t          ",
            "      t:::::t    tttttt",
            "      t::::::tttt:::::t",
            "      tt::::::::::::::t",
            "        tt:::::::::::tt",
            "          ttttttttttt  ",
            "                       ",
            "                       ",
            "                       ",
            "                       ",
            "                       ",
            "                       ",
            "                       ",
        });
        asciiMap.put('u', new String[]{
            "                  ",
            "                  ",
            "                  ",
            "                  ",
            "                  ",
            "uuuuuu    uuuuuu  ",
            "u::::u    u::::u  ",
            "u::::u    u::::u  ",
            "u::::u    u::::u  ",
            "u::::u    u::::u  ",
            "u::::u    u::::u  ",
            "u::::u    u::::u  ",
            "u:::::uuuu:::::u  ",
            "u:::::::::::::::uu",
            " u:::::::::::::::u",
            "  uu::::::::uu:::u",
            "    uuuuuuuu  uuuu",
            "                  ",
            "                  ",
            "                  ",
            "                  ",
            "                  ",
            "                  ",
            "                  ",
        });
        asciiMap.put('v', new String[]{
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "vvvvvvv           vvvvvvv",
            " v:::::v         v:::::v ",
            "  v:::::v       v:::::v  ",
            "   v:::::v     v:::::v   ",
            "    v:::::v   v:::::v    ",
            "     v:::::v v:::::v     ",
            "      v:::::v:::::v      ",
            "       v:::::::::v       ",
            "        v:::::::v        ",
            "         v:::::v         ",
            "          v:::v          ",
            "           vvv           ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
        });
        asciiMap.put('w', new String[]{
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "wwwwwww           wwwww           wwwwwww",
            " w:::::w         w:::::w         w:::::w ",
            "  w:::::w       w:::::::w       w:::::w  ",
            "   w:::::w     w:::::::::w     w:::::w   ",
            "    w:::::w   w:::::w:::::w   w:::::w    ",
            "     w:::::w w:::::w w:::::w w:::::w     ",
            "      w:::::w:::::w   w:::::w:::::w      ",
            "       w:::::::::w     w:::::::::w       ",
            "        w:::::::w       w:::::::w        ",
            "         w:::::w         w:::::w         ",
            "          w:::w           w:::w          ",
            "           www             www           ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
        });
        asciiMap.put('x', new String[]{
            "                    ", 
            "                    ", 
            "                    ", 
            "                    ", 
            "                    ", 
            "xxxxxxx      xxxxxxx",
            " x:::::x    x:::::x ",
            "  x:::::x  x:::::x  ",
            "   x:::::xx:::::x   ",
            "    x::::::::::x    ",
            "     x::::::::x     ",
            "     x::::::::x     ",
            "    x::::::::::x    ",
            "   x:::::xx:::::x   ",
            "  x:::::x  x:::::x  ",
            " x:::::x    x:::::x ",
            "xxxxxxx      xxxxxxx",
            "                    ",
            "                    ", 
            "                    ", 
            "                    ", 
            "                    ", 
            "                    ", 
            "                    ",
        });
        asciiMap.put('y', new String[]{
            "                         ",  
            "                         ",  
            "                         ",  
            "                         ",  
            "                         ",  
            "yyyyyyy           yyyyyyy", 
            " y:::::y         y:::::y ", 
            "  y:::::y       y:::::y  ", 
            "   y:::::y     y:::::y   ", 
            "    y:::::y   y:::::y    ", 
            "     y:::::y y:::::y     ", 
            "      y:::::y:::::y      ", 
            "       y:::::::::y       ", 
            "        y:::::::y        ", 
            "         y:::::y         ", 
            "        y:::::y          ", 
            "       y:::::y           ", 
            "      y:::::y            ", 
            "     y:::::y             ", 
            "    y:::::y              ", 
            "   y:::::y               ", 
            "  yyyyyyy                ", 
            "                         ",   
            "                         ", 
        });
        asciiMap.put('z', new String[]{
            "                 ", 
            "                 ", 
            "                 ", 
            "                 ", 
            "                 ", 
            "zzzzzzzzzzzzzzzzz", 
            "z:::::::::::::::z", 
            "z::::::::::::::z ", 
            "zzzzzzzz::::::z  ", 
            "      z::::::z   ", 
            "     z::::::z    ", 
            "    z::::::z     ", 
            "   z::::::z      ", 
            "  z::::::zzzzzzzz", 
            " z::::::::::::::z", 
            "z:::::::::::::::z", 
            "zzzzzzzzzzzzzzzzz", 
            "                 ", 
            "                 ", 
            "                 ", 
            "                 ", 
            "                 ", 
            "                 ", 
            "                 ", 
        });
        asciiMap.put('0', new String[]{
            "                   ",
            "     000000000     ",
            "   00:::::::::00   ",
            " 00:::::::::::::00 ",
            "0:::::::000:::::::0",
            "0::::::0   0::::::0",
            "0:::::0     0:::::0",
            "0:::::0     0:::::0",
            "0:::::0 000 0:::::0",
            "0:::::0 000 0:::::0",
            "0:::::0     0:::::0",
            "0:::::0     0:::::0",
            "0::::::0   0::::::0",
            "0:::::::000:::::::0",
            " 00:::::::::::::00 ",
            "   00:::::::::00   ",
            "     000000000     ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
        });
        asciiMap.put('1', new String[]{
            "            ",
            "  1111111   ",
            " 1::::::1   ",
            "1:::::::1   ",
            "111:::::1   ",
            "   1::::1   ",
            "   1::::1   ",
            "   1::::1   ",
            "   1::::l   ",
            "   1::::l   ",
            "   1::::l   ",
            "   1::::l   ",
            "   1::::l   ",
            "111::::::111",
            "1::::::::::1",
            "1::::::::::1",
            "111111111111",
            "            ",
            "            ",
            "            ",
            "            ",
            "            ",
            "            ",
            "            ",
        });
        asciiMap.put('2', new String[]{
            "                    ",
            " 222222222222222    ",
            "2:::::::::::::::22  ",
            "2::::::222222:::::2 ",
            "2222222     2:::::2 ",
            "            2:::::2 ",
            "            2:::::2 ",
            "         2222::::2  ",
            "    22222::::::22   ",
            "  22::::::::222     ",
            " 2:::::22222        ",
            "2:::::2             ",
            "2:::::2             ",
            "2:::::2       222222",
            "2::::::2222222:::::2",
            "2::::::::::::::::::2",
            "22222222222222222222",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
        });
        asciiMap.put('3', new String[]{
            "                   ",
            " 333333333333333   ",
            "3:::::::::::::::33 ",
            "3::::::33333::::::3",
            "3333333     3:::::3",
            "            3:::::3",
            "            3:::::3",
            "    33333333:::::3 ",
            "    3:::::::::::3  ",
            "    33333333:::::3 ",
            "            3:::::3",
            "            3:::::3",
            "            3:::::3",
            "3333333     3:::::3",
            "3::::::33333::::::3",
            "3:::::::::::::::33 ",
            " 333333333333333   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
        });
        asciiMap.put('4', new String[]{
            "                  ",
            "       444444444  ",
            "      4::::::::4  ",
            "     4:::::::::4  ",
            "    4::::44::::4  ",
            "   4::::4 4::::4  ",
            "  4::::4  4::::4  ",
            " 4::::4   4::::4  ",
            "4::::444444::::444",
            "4::::::::::::::::4",
            "4444444444:::::444",
            "          4::::4  ",
            "          4::::4  ",
            "          4::::4  ",
            "        44::::::44",
            "        4::::::::4",
            "        4444444444",
            "                  ",
            "                  ",
            "                  ",
            "                  ",
            "                  ",
            "                  ",
            "                  ",
        });
        asciiMap.put('5', new String[]{
            "                   ",
            "555555555555555555 ",
            "5::::::::::::::::5 ",
            "5::::::::::::::::5 ",
            "5:::::555555555555 ",
            "5:::::5            ",
            "5:::::5            ",
            "5:::::5555555555   ",
            "5:::::::::::::::5  ",
            "555555555555:::::5 ",
            "            5:::::5",
            "            5:::::5",
            "5555555     5:::::5",
            "5::::::55555::::::5",
            " 55:::::::::::::55 ",
            "   55:::::::::55   ",
            "     555555555     ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
        });
        asciiMap.put('6', new String[]{
            "                   ",
            "        66666666   ",
            "       6::::::6    ",
            "      6::::::6     ",
            "     6::::::6      ",
            "    6::::::6       ",
            "   6::::::6        ",
            "  6::::::6         ",
            " 6::::::::66666    ",
            "6::::::::::::::66  ",
            "6::::::66666:::::6 ",
            "6:::::6     6:::::6",
            "6:::::6     6:::::6",
            "6::::::66666::::::6",
            " 66:::::::::::::66 ",
            "   66:::::::::66   ",
            "     666666666     ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
        });
        asciiMap.put('7', new String[]{
            "                    ", 
            "77777777777777777777",
            "7::::::::::::::::::7",
            "7::::::::::::::::::7",
            "777777777777:::::::7",
            "           7::::::7 ",
            "          7::::::7  ",
            "         7::::::7   ",
            "        7::::::7    ",
            "       7::::::7     ",
            "      7::::::7      ",
            "     7::::::7       ",
            "    7::::::7        ",
            "   7::::::7         ",
            "  7::::::7          ",
            " 7::::::7           ",
            "77777777            ",
            "                    ",
            "                    ", 
            "                    ", 
            "                    ", 
            "                    ", 
            "                    ", 
            "                    ",  
        });
        asciiMap.put('8', new String[]{
            "                   ",
            "     888888888     ",
            "   88:::::::::88   ",
            " 88:::::::::::::88 ",
            "8::::::88888::::::8",
            "8:::::8     8:::::8",
            "8:::::8     8:::::8",
            " 8:::::88888:::::8 ",
            "  8:::::::::::::8  ",
            " 8:::::88888:::::8 ",
            "8:::::8     8:::::8",
            "8:::::8     8:::::8",
            "8:::::8     8:::::8",
            "8::::::88888::::::8",
            " 88:::::::::::::88 ",
            "   88:::::::::88   ",
            "     888888888     ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
        });
        asciiMap.put('9', new String[]{
            "                   ",
            "     999999999     ",
            "   99:::::::::99   ",
            " 99:::::::::::::99 ",
            "9::::::99999::::::9",
            "9:::::9     9:::::9",
            "9:::::9     9:::::9",
            " 9:::::99999::::::9",
            "  99::::::::::::::9",
            "    99999::::::::9 ",
            "         9::::::9  ",
            "        9::::::9   ",
            "       9::::::9    ",
            "      9::::::9     ",
            "     9::::::9      ",
            "    9::::::9       ",
            "   99999999        ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
        });
        
    }
    
    

    
}
